using IPRO.Admin.Models;
using IPRO.DataAccess.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IPRO.Admin.Controllers;

[Authorize]
public class PayPalSetupController : Controller
{
    private readonly IUnitOfWork _uow;
    private readonly IConfiguration _configuration;
    private readonly IWebHostEnvironment _environment;

    public PayPalSetupController(IUnitOfWork uow, IConfiguration configuration, IWebHostEnvironment environment)
    {
        _uow = uow;
        _configuration = configuration;
        _environment = environment;
    }

    public async Task<IActionResult> Index()
    {
        var clientId = _configuration["PayPal:ClientId"] ?? string.Empty;
        var clientSecret = _configuration["PayPal:ClientSecret"] ?? string.Empty;
        var webhookId = _configuration["PayPal:WebhookId"] ?? string.Empty;
        var returnUrl = _configuration["PayPal:ReturnUrl"] ?? string.Empty;
        var cancelUrl = _configuration["PayPal:CancelUrl"] ?? string.Empty;
        var baseUrl = _configuration["PayPal:BaseUrl"] ?? string.Empty;
        var packages = (await _uow.BillingRules.GetAllAsync())
            .OrderBy(p => p.MonthlyPrice <= 0 ? decimal.MaxValue : p.MonthlyPrice)
            .ThenBy(p => p.PackageName)
            .Select(PayPalPackagePlanStatusViewModel.FromRule)
            .ToList();

        var model = new PayPalSetupViewModel
        {
            IsSandbox = string.Equals(_configuration["PayPal:IsSandbox"], "true", StringComparison.OrdinalIgnoreCase),
            BaseUrl = baseUrl,
            ClientIdPreview = Mask(clientId),
            HasClientId = !string.IsNullOrWhiteSpace(clientId),
            HasClientSecret = !string.IsNullOrWhiteSpace(clientSecret),
            WebhookIdPreview = Mask(webhookId),
            HasWebhookId = !string.IsNullOrWhiteSpace(webhookId),
            ReturnUrl = returnUrl,
            CancelUrl = cancelUrl,
            ExpectedWebhookUrl = BuildWebhookUrl(returnUrl, cancelUrl),
            EnvironmentName = _environment.EnvironmentName,
            Packages = packages
        };

        model.ActivePackageCount = packages.Count(p => p.IsActive);
        model.MissingMonthlyPlanCount = packages.Count(p => p.NeedsMonthlyPlan);
        model.MissingAnnualPlanCount = packages.Count(p => p.NeedsAnnualPlan);
        model.Settings = BuildSettingStatuses(model, clientSecret);

        return View(model);
    }

    private static List<PayPalSettingStatusViewModel> BuildSettingStatuses(PayPalSetupViewModel model, string clientSecret) =>
    [
        new()
        {
            Name = "PayPal__IsSandbox",
            Value = model.IsSandbox ? "true" : "false",
            IsConfigured = true,
            HelpText = "Must match the PayPal app type. Sandbox credentials require true; live credentials require false."
        },
        new()
        {
            Name = "PayPal__BaseUrl",
            Value = string.IsNullOrWhiteSpace(model.BaseUrl) ? "Missing" : model.BaseUrl,
            IsConfigured = !string.IsNullOrWhiteSpace(model.BaseUrl),
            HelpText = "Sandbox usually uses https://api-m.sandbox.paypal.com. Live uses https://api-m.paypal.com."
        },
        new()
        {
            Name = "PayPal__ClientId",
            Value = model.ClientIdPreview,
            IsConfigured = model.HasClientId,
            HelpText = "REST app Client ID from the same PayPal sandbox or live app."
        },
        new()
        {
            Name = "PayPal__ClientSecret",
            Value = string.IsNullOrWhiteSpace(clientSecret) ? "Missing" : "Configured",
            IsConfigured = !string.IsNullOrWhiteSpace(clientSecret),
            HelpText = "REST app secret. Hidden here on purpose."
        },
        new()
        {
            Name = "PayPal__WebhookId",
            Value = model.WebhookIdPreview,
            IsConfigured = model.HasWebhookId,
            HelpText = "Required for verified PayPal webhooks."
        },
        new()
        {
            Name = "PayPal__ReturnUrl",
            Value = string.IsNullOrWhiteSpace(model.ReturnUrl) ? "Generated by app during checkout" : model.ReturnUrl,
            IsConfigured = true,
            HelpText = "Optional default return URL. The web app also sends live checkout-specific return URLs."
        },
        new()
        {
            Name = "PayPal__CancelUrl",
            Value = string.IsNullOrWhiteSpace(model.CancelUrl) ? "Generated by app during checkout" : model.CancelUrl,
            IsConfigured = true,
            HelpText = "Optional default cancel URL. The web app also sends live checkout-specific cancel URLs."
        }
    ];

    private static string BuildWebhookUrl(string returnUrl, string cancelUrl)
    {
        var source = string.IsNullOrWhiteSpace(returnUrl) ? cancelUrl : returnUrl;
        return Uri.TryCreate(source, UriKind.Absolute, out var uri)
            ? $"{uri.Scheme}://{uri.Host}{(uri.IsDefaultPort ? string.Empty : ":" + uri.Port)}/Billing/Webhook"
            : "https://ipro-prod-web.azurewebsites.net/Billing/Webhook";
    }

    private static string Mask(string value)
    {
        if (string.IsNullOrWhiteSpace(value)) return "Missing";
        if (value.Length <= 10) return $"{value[..Math.Min(3, value.Length)]}...";
        return $"{value[..6]}...{value[^4..]}";
    }
}
