namespace IPRO.DataAccess;

// 495 (2026-09-18): the Generic edition's starter library -- eight articles in two categories, written
// for the clients of ANY professional-service business (a consultant, a designer, a contractor, a
// lawyer, a coach...). The rules every one of them keeps, pinned by GenericStarterPackTests: nothing
// that names an industry, no regulated advice, no figures, years, prices or promises, and only plain
// markup (p, h3, ul, li, strong). WebsiteStarterArticleSeeder adds them per title, so they reach a
// database that was seeded long ago; SuperAdmin edits them afterwards under Starter Content like
// any other starter article. The two shared "All" articles still reach a Generic adviser as well.
public static class GenericStarterArticles
{
    public sealed record Entry(string Title, string Category, string Summary, string Content);

    public static readonly Entry[] All =
    {
        new("What to Expect When You Start Working With Us",
            "Working Together",
            "The first few weeks of working with us follow a simple pattern, from the opening conversation to how updates reach you.",
            """
            <p>Starting work with someone new always involves a little uncertainty, mostly because you don't yet know how things will run. Here's what the first few weeks with us look like, so you know what's coming.</p><h3>It starts with a conversation</h3><p>After your inquiry, the first step is simply to talk. We'll ask what prompted you to get in touch, what you're hoping to achieve, and what you've already tried. You don't need to arrive with a finished plan. A clear picture of where things stand today is enough for us to work from.</p><p>We'll also tell you plainly if we don't think we're the right fit. It's better for everyone to find that out at the beginning.</p><h3>We agree on what's included</h3><p>Next, we settle what the work covers and, just as usefully, what it doesn't. We'll set this out in plain language before we begin, so both of us are working from the same list.</p><p>If your needs change along the way, that's normal. We'll talk about what the change involves before anything is added, not after.</p><h3>You'll know who to talk to</h3><p>From the start, you'll have a main contact: one person who knows where your work stands and can either answer your question or find the person who can. Often that's the same person you first spoke with.</p><h3>How updates reach you</h3><p>Early on, we'll ask how you'd like to hear from us — by email, by phone, or at a regular check-in — and roughly how often. Some people want to follow every step. Others would rather hear from us only when there's a decision to make or something to review. Either is fine. What matters is that we agree on it up front, so you're not left wondering where things stand.</p><h3>What we'll need from you</h3><p>Good work depends on good information. In the first weeks, we'll likely ask you for:</p><ul><li><strong>Background.</strong> Any documents, notes or history that explain how you got here.</li><li><strong>Access.</strong> A way to reach the people, places or information we need to do the work.</li><li><strong>Decisions.</strong> Timely answers when there's a choice to make, and clarity about who on your side has the final say.</li><li><strong>Candour.</strong> If something isn't sitting right, tell us early, while it's still easy to adjust.</li></ul><h3>Questions are welcome at any point</h3><p>You're never expected to nod along. If a term is unfamiliar, a step seems unnecessary, or you simply want to know why we're recommending something, ask, whenever it occurs to you. We'd much rather explain something twice than have you wonder about it.</p><p>The first few weeks set the tone for everything that follows. By the end of them, you should know what we're doing, why we're doing it, and how to reach us.</p>
            """),
        new("How to Brief Us So You Get What You Need",
            "Working Together",
            "A good brief covers the outcome you want, your constraints, a few examples, who decides and what finished looks like.",
            """
            <p>A brief is simply your explanation of what you need and why. It doesn't have to be long or polished, but what goes into it shapes everything that comes after. Here's what helps us most.</p><h3>Start with the outcome, not the solution</h3><p>Most people arrive with a solution already in mind, which is natural. It's more useful to start with what you want to be different once the work is done: what's taking too much of your time, what's worrying you, what you'd like to be able to do. A request for a particular thing tells us what to produce. The problem behind it tells us what to solve, and there may be a simpler way to get there than the one you first thought of.</p><p>If you do have a solution in mind, tell us that too, along with the reason behind it.</p><h3>Tell us your constraints</h3><p>Constraints are helpful, not awkward. They let us recommend something that fits your situation rather than something that's ideal only on paper. The most useful ones to share:</p><ul><li><strong>Time.</strong> Tell us if there's a date this truly has to be ready by, and what's driving it.</li><li><strong>Budget range.</strong> Even a rough range helps. It lets us suggest the most sensible approach within it instead of guessing high or low.</li><li><strong>Must-haves.</strong> Anything that isn't negotiable, along with anything you already know you don't want.</li></ul><h3>Show us what you like and what you don't</h3><p>Examples save a lot of words. If you've seen something close to what you have in mind, or worked with someone whose approach suited you, tell us what you liked about it. Examples of what you don't like are just as valuable; they often reveal preferences that are hard to put into words.</p><h3>Tell us who decides</h3><p>Let us know early who has the final say, and who else needs to be consulted. If a business partner, a family member or a board will weigh in before anything is approved, it's far easier to involve them at the beginning than to discover their views at the end.</p><h3>Describe what "done" looks like</h3><p>Finally, tell us how you'll know the work is finished. It might be something you can hold in your hands, a decision you feel ready to make, or a problem that has stopped coming back. When we share the same picture of "done," it's much easier to plan the steps in between and to recognize when we've arrived.</p><h3>If you're not sure, say so</h3><p>You won't have answers to all of this, and that's fine. Tell us what you know and flag what you don't. A brief with honest question marks is far more useful than one that sounds certain and isn't.</p><p>If writing isn't your thing, talk it through with us instead, and we'll summarize what we heard for you to correct.</p>
            """),
        new("Quotes, Estimates and Scope: What the Words Mean",
            "Working Together",
            "We explain estimate, quote and scope in plain language, and why a change to the work changes the price or the timeline.",
            """
            <p>Three words come up at the start of almost any piece of work: estimate, quote and scope. They're often used as if they mean the same thing. Here's what we mean by each, in plain language.</p><h3>An estimate is an informed guess</h3><p>An estimate is our best sense of what something is likely to cost or how long it's likely to take, based on what we know at the time. It's given before all the details are known, so it can move, up or down, as the picture becomes clearer.</p><p>A good estimate comes with its assumptions, so you can see what would make it change.</p><h3>A quote is a commitment</h3><p>A quote is firmer: a stated price for a defined piece of work. Because it's a commitment, we need to know precisely what we're committing to, so a quote usually follows a more detailed conversation than an estimate does.</p><p>If you need a firm figure before going ahead, tell us, and we'll talk about what we'd need to know first. If a rough idea is enough to plan with, an estimate will do.</p><h3>Scope is the list of what's included</h3><p>Scope is the description of the work itself: what will be done, what you'll receive, and where the edges are. A clear scope also says what is not included, because that's where misunderstandings tend to start. It deserves as careful a read as the price.</p><h3>Why a change in scope changes the price or timeline</h3><p>A price and the scope behind it are two halves of the same thing. If the work grows — an extra piece, a new requirement, a change of direction — the time and effort behind the original figure no longer match what's being asked for. Something has to give: the price, the timeline, or another part of the work.</p><p>That isn't a penalty, and it isn't anyone's fault; needs change. It works in reverse, too: if the work shrinks, it's fair to ask what that does to the price.</p><h3>How to ask for a change without friction</h3><ul><li><strong>Raise it early.</strong> A change is nearly always easier to absorb before the affected work is done than after.</li><li><strong>Describe what you need and why.</strong> The reason often points to a simpler way of getting there.</li><li><strong>Ask what it affects.</strong> We'll tell you what the change does to the price and the timeline before you decide.</li><li><strong>Put it in writing.</strong> A short note both of us can refer to later keeps everyone's memory honest.</li></ul><p>None of this is meant to make change difficult. It's there so that when the work changes, both of us know what we've agreed to.</p><p>This is a general explanation of how these words are commonly used, not legal advice. If a term in anything we send you is unclear, ask and we'll explain what we mean.</p>
            """),
        new("How to Give Feedback That Gets Results",
            "Working Together",
            "Useful feedback is specific, early and consolidated, and it separates what must change from what would be nice to have.",
            """
            <p>At some point we'll show you something — a draft, a plan, a proposal, a first version — and ask what you think. What you say next has a real effect on how smoothly the work moves from there. Good feedback isn't about being polite or being tough. It's about being useful.</p><h3>Be specific</h3><p>"I'm not sure about this" tells us something is wrong but not where to look. Point to the exact section, step or choice of words you're reacting to, and the conversation gets easier right away.</p><p>The same goes for what's working. When you tell us what you like, we know what to protect while we change the rest.</p><h3>Describe the problem, not the fix</h3><p>It's tempting to hand over a solution: move this, cut that, add more here. Sometimes that's exactly right. More often, the most helpful thing you can tell us is what isn't working and why. "This feels too complicated for the people who'll use it" gives us more to work with than "make it shorter," because there may be several ways to solve the problem, and one of them may suit you better than the first that comes to mind.</p><p>You know your situation better than we do. Finding the right fix is our half of the job.</p><h3>Gather everyone's comments into one reply</h3><p>If several people on your side have views, collect them before replying, and settle any disagreements among yourselves first. When comments arrive separately, they often contradict each other, and we're left guessing whose view carries the day. One consolidated reply, from one person, saves time on both sides.</p><h3>Give it early</h3><p>Rough work is meant to be reacted to. A concern raised at the outline stage can be dealt with in a conversation; the same concern raised at the end can mean redoing finished work. If something seems off, say so as soon as you notice it, even if you can't yet explain why. A half-formed doubt shared early is worth more than a polished critique that arrives late.</p><h3>Separate must-change from nice-to-have</h3><p>Not every comment carries the same weight, and it helps a great deal when you tell us which is which. A simple split works well:</p><ul><li><strong>Must change.</strong> Anything that's wrong, missing, or that you can't approve as it stands.</li><li><strong>Nice to have.</strong> Preferences and ideas you'd like us to consider if time and budget allow.</li></ul><p>That helps us prioritize: we put our effort where it matters most to you, and we can be candid about what the smaller items would involve.</p><h3>A word on honesty</h3><p>You won't hurt our feelings. We'd far rather hear plainly that something has missed the mark than find out later that you lived with it quietly. Feedback is part of the work, not an interruption to it, and there's always room for it.</p>
            """),
        new("Five Signs It Is Time to Bring In Outside Help",
            "Practical Guides",
            "Five practical signs that a task has outgrown the do-it-yourself approach, plus the situations where handling it yourself is perfectly reasonable.",
            """
            <p>Doing things yourself is often the right call. You know your situation better than anyone, and plenty of work doesn't need a specialist. Still, there's usually a point where handling it alone stops saving money and starts costing it. These five signs tend to show up around then.</p><h3>1. The work keeps slipping</h3><p>It has been on your list for weeks, and something more urgent always pushes it down. That's rarely a lack of discipline. More often, the task doesn't fit into the time you have. If it matters and it isn't moving, handing it to someone whose job is to move it is a reasonable fix.</p><h3>2. It needs skills you don't have</h3><p>No person or team has every skill. Learning a new one is worthwhile when you'll use it again and again, and a poor trade when the task comes up rarely and you'd be starting from scratch each time. Someone who does the work every day will usually get there sooner, and with fewer wrong turns.</p><h3>3. A mistake would be costly</h3><p>Some work is forgiving: if it goes wrong, you fix it and carry on. Other work isn't. An error might be expensive to undo, slow to surface, or visible to the very people you want to impress. The more a mistake would cost, the stronger the case for someone who has seen the pitfalls before.</p><h3>4. The delay is costing more than the help would</h3><p>Unfinished work has a price, even when no invoice arrives for it. It might be an opportunity you can't pursue yet, a decision left on hold, or just the worry of knowing it's still undone. Put a rough value on the wait, then compare it with what outside help would cost.</p><h3>5. You need a fresh pair of eyes</h3><p>When you've been close to something for a long time, it gets hard to see it plainly. An outsider has no stake in how things have always been done, and can ask the obvious questions everyone else stopped asking. Sometimes a second opinion confirms you were right all along — which is worth knowing too.</p><h3>When doing it yourself makes sense</h3><p>None of this means handing over everything. Doing the work yourself is perfectly reasonable when:</p><ul><li>The task is small, low-risk and easy to correct if it goes wrong.</li><li>You enjoy it, or you want to build the skill for the long run.</li><li>It depends on knowledge that only you or your team have.</li><li>You have the time, and nothing important is waiting on it.</li></ul><p>There's also a middle path: do most of it yourself, and bring someone in for the part that worries you.</p><p>If you recognize a few of these signs and aren't sure which way to go, we're happy to talk it through. Sometimes the honest answer is that you're fine on your own, and we're glad to say so.</p>
            """),
        new("Keeping Your Documents and Records Organized",
            "Practical Guides",
            "A few plain habits for storing, naming and backing up your documents so you can find what you need when you need it.",
            """
            <p>Nobody sets out to have messy records. It happens one file at a time: an attachment saved to the desktop, a contract in someone's inbox, three versions of the same document with no clue which one is current. The fix isn't elaborate. A few plain habits, kept up consistently, will do more than any clever system.</p><h3>Give everything one home</h3><p>Pick a single place where your documents live — a shared drive, a cloud folder or a filing cabinet — and make it the only place. The test is simple: if you were away for a week, could someone else find what they need without calling you? Paper counts too. Either scan it into the same system or note where the original is kept.</p><h3>Use names that make sense a year from now</h3><p>A good file name tells you what the document is without opening it. Include what it is, who it's from and the date, and use the same pattern every time. If the date comes first, written year-month-day, files sort themselves into order. Avoid names like "scan" or "new version", which mean something today and nothing next spring.</p><h3>Keep the folder structure simple</h3><p>A handful of top-level folders is usually enough: by year, by project, or by the kind of document, whichever matches how you look for things. Resist the urge to build deep layers of subfolders. If you have to click more than three or four times to reach a file, the structure is working against you.</p><h3>Separate the final version from the drafts</h3><p>Drafts are useful while the work is under way and a nuisance afterwards. Once something is signed, sent or approved, save that version somewhere clearly marked as final, and move the drafts into their own folder. Anyone opening the file later should never have to guess which copy is the real one.</p><h3>Test your backup</h3><p>A backup you've never restored from is a hope, not a backup. Every so often, try to recover a file as though the original were gone. It's the only way to know the copy is really there, is current, and can be opened. Keep one copy somewhere other than where your main files live.</p><h3>Tidy up on a schedule</h3><p>Put a short, recurring appointment in your calendar to file strays, rename anything vague and archive what's finished. Little and often beats an annual rescue mission. If you're not sure whether something can go, move it to an archive folder rather than deleting it. How long a document should be kept depends on what it is, and the relevant professional can tell you.</p><p>If we're working together and you're not sure what we'll need from you or in what form, just ask. It's much easier to set things up well at the start than to untangle them later.</p>
            """),
        new("Getting Ready for a Project: A Simple Checklist",
            "Practical Guides",
            "Six things worth thinking through before a project begins, from the outcome you want to how you would like to be kept updated.",
            """
            <p>When a project struggles, the cause can often be traced back to something left unsaid at the start: an assumption about the budget, a deadline nobody mentioned, a decision-maker who appeared late. A little thinking before we begin can save a good deal of backtracking afterwards.</p><p>Here are six things worth thinking through before any project starts. You don't need polished answers. Rough notes are fine, and "I'm not sure yet" is a useful answer too — it tells us where the conversation should begin.</p><h3>The checklist</h3><ul><li><strong>The outcome you want.</strong> Describe what will be different when the project is finished, rather than the steps to get there. A useful test is to say what would make you look back and call it a success. That gives both of us a way to judge every later decision.</li><li><strong>A realistic budget range.</strong> A range is more useful than a single figure. Sharing it early lets us suggest an approach that fits, rather than one that has to be cut back later. If you have no idea what's reasonable, say so, and we can talk about what drives the cost.</li><li><strong>A deadline, and what drives it.</strong> Tell us when you need the work done and why that date matters: an event, a season, another piece of work that depends on this one. A fixed date and a preferred date are planned for differently, so it helps to know which one this is.</li><li><strong>Who decides, and who needs to be consulted.</strong> Name the person who gives the final yes. Then list anyone whose opinion has to be heard along the way: a partner, a colleague, a board, a family member. Bringing them in early is far easier than reopening finished work because someone saw it late.</li><li><strong>The materials and access we'll need.</strong> Depending on the work, that might be documents, background information, earlier work on the same problem, or access to a space, a system or the people who know the details. Gathering these before the start date means the early days aren't spent waiting.</li><li><strong>How you'd like to be kept updated.</strong> Some people want a short note every week; others only want to hear when there's a decision to make or a problem to solve. Tell us which you prefer, how you like to be reached, and who else should be copied.</li></ul><h3>What to do with your answers</h3><p>Write them down, even as a few lines, and share them with us before we start. We'll likely have questions of our own, and some of your answers may shift once we've talked. That's fine. It's far better for a plan to change on paper at the start than halfway through the work.</p><p>If any item is hard to answer, that's worth knowing too. Bring it to our first conversation and we'll work through it together.</p>
            """),
        new("Why a Regular Check-In Is Worth Your Time",
            "Practical Guides",
            "A short, scheduled review helps catch small things early, keeps the work pointed at what matters now, and makes room for overlooked questions.",
            """
            <p>Most changes don't announce themselves. A priority shifts, someone new gets involved, a plan that made sense last year quietly stops fitting, and none of it feels big enough to pick up the phone about. Then one day the gap between how things are and how they were set up has become a problem of its own.</p><p>A regular check-in is a simple guard against that. It's a short, scheduled conversation with no crisis attached — a chance to compare notes on where things stand and whether our work for you still fits what you need.</p><h3>Catching small things early</h3><p>Many large problems were once small ones that nobody had a reason to mention. A scheduled review creates the reason. When we look at things together at regular intervals, a minor issue tends to get noticed while it's still quick and inexpensive to deal with, rather than after it has grown.</p><h3>Keeping the work pointed at what matters now</h3><p>What you needed when we first spoke may not be what you need today. Your goals may have moved, or something outside your control may have changed the picture. A check-in lets us adjust course in small steps, instead of discovering much later that we've been working carefully toward the wrong target.</p><h3>Room for the questions that never felt urgent</h3><p>Everyone keeps a mental list of things they've been meaning to ask. They're rarely pressing enough to justify a call or an email, so they wait, sometimes for a very long time. A check-in is the natural home for them. Often those are the most valuable minutes of the conversation, because a small question can point to something that deserves a closer look.</p><h3>It doesn't need to be long</h3><p>A check-in can be a brief call or a short meeting. Sometimes the conclusion is simply that everything is on track and nothing needs to change. That's a perfectly good result: you leave knowing it rather than assuming it.</p><h3>What to bring</h3><p>You don't need to prepare much. A few notes will do:</p><ul><li><strong>What has changed</strong> since we last spoke, even if it seems unrelated.</li><li><strong>What's coming up</strong> over the next while: plans, decisions, deadlines.</li><li><strong>What's been bothering you</strong>, including anything about how we work together.</li><li><strong>Anything you didn't fully understand</strong>, whether it came from us or from someone else.</li><li><strong>Your list of small questions</strong>, however minor they seem.</li></ul><p>How often to meet depends on how quickly things move for you. For some people once a year is plenty; for others a shorter, more frequent conversation works better. If you'd like to set up a regular check-in, or you feel one is overdue, get in touch and we'll find a time.</p>
            """),
    };
}
