// <auto-generated />
using IPRO.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IPRO.DataAccess.Migrations
{
    [DbContext(typeof(IPRODbContext))]
    [Migration("20260707173000_AddClientFollowUps")]
    partial class AddClientFollowUps
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
